### ISSUE TITLE
importing file using read_geno

### ISSUE THREAD

**Issue by alinedclm** [mmollina/MAPpoly#3]
Hi Mollinari, I am looking for an example of MAPpoly input file for the function read_geno. I saw that the hexafake object is a list of class "mappoly.data". I obtained a list for my data with the same structure but I could not import into MAPpoly.

I tried:

data.file <- system.file(my_data, package = "mappoly")
data <- read_geno(file.in = data.file)

the output was:

Error in scan(file.in, what = character(), sep = " ", nlines = 1, quiet = TRUE) : 
 'file' must be a character string or connection

Is it possible to work directly in the R without save intermediate files as .txt? Do you have an example of how convert a class(file) as list into a class(file) as mappoly.data?

Thank you.

**Comment by mmollina** [comment]
You can find the input file associated to 'hexafake' at https://github.com/mmollina/MAPpoly/blob/master/inst/extdata/hexafake

If you have a list with the same structure as 'hexafake', you can use 

data <- structure(your_list, class = "mappoly.map")

**Comment by mmollina** [comment]
I've just implemented the function 'read_geno_csv'. I believe this is a much more straightforward way to load your dataset into MAPpoly.
Please let me know if any of the solutions proposed here works for you so that I can close the issue. Thanks!

**Comment by alinedclm** [comment]
Hi Mollinari, I was able to import the data using structure function. I just want to emphasize that it just worked like:

  date <- structure (your_list, class = "mappoly.**data**").

In the first message you had suggested

date <- structure (your_list, class = "mappoly.**map**")

Thank you for the quick answer!

**Comment by mmollina** [comment]
My mistake. Fixed in the original post. Thanks
