### ISSUE TITLE
mrk_chisq_test crashing read_geno_dist

### ISSUE THREAD

**Issue by rramadeu** [mmollina/MAPpoly#4]
Hi Marcelo,

The `read_geno_dist()` function is crashing when trying to read some data with the following message:

`if(any(p < 0)) stop("probabilities must be non-negative.").`

I modified the `mrk_chisq_test `in my `mappoly` fork and apparently this issue was solved. My workaround: Instead of `mrk_chisq_test` crashes, put an NA in the place with `tryCatch()` structure.

I can send you the data that is generating the error to figure out the problem or do a pull request with this workaround. It was just a dozen out of 20k markers that were generating this issue.

Cheers,
Rodrigo

**Comment by mmollina** [comment]
Can you send me the data, please?

**Comment by mmollina** [comment]
Solved in [this](https://github.com/mmollina/MAPpoly/commit/c24f93403603b2afea8e5cd57b4b49590db6f58e) commit.
