### ISSUE TITLE
est_rf_pairwise n.batches=1 and n.batches>1 gives different results

### ISSUE THREAD

**Issue by jeekinlau** [mmollina/MAPpoly#44]
I discovered that in the est_rf_pairwise function when n.batch>1, the resulting all.rf.pairwise$pairwise object and the resulting mat$rec.mat and mat$lod.mat objects are off by 1 marker. Must be an issue in the concatenation of the separate batches. I  tried to look through the est_rf_pairwise function code but it was too complicated for me to spot where the error is. Attached is a picture of the resulting mat$rec.mat matrix where you can see on the left is the run with n.batch=1 and on the right is n.batch=2. looks like there is an extra row and and extra column and everything is shifted down one and to the right one. It appears when n.batch>1 that all the pairwise comparisons with the first marker is given the value NA even in the all.rf.pairwise$pairwise object. 

thanks
![Screenshot 2021-06-28 083342](https://user-images.githubusercontent.com/77897366/123645106-a4606800-d7eb-11eb-8787-8fe81952fa37.png)
![Screenshot 2021-06-28 083740](https://user-images.githubusercontent.com/77897366/123645726-2f416280-d7ec-11eb-9e09-49b56b5d3847.png)

**Comment by mmollina** [comment]
Function est_pairwise_rf2 solves this problem. n.batches argument is no longer available in function est_pairwise_rf.
