### ISSUE TITLE
Can MAPpoly fit single generation of selfing population in tetraploidy potato？

### ISSUE THREAD

**Issue by baozg** [mmollina/MAPpoly#45]
Hi, @mmollina 

When `MAPpoly` loading data from the `fitPoly`, it need set the parent1 and parent2 for chi-square test, but we only can set one individual for parent when using the selfing population. Do you have any suggestion for this issue?

Thanks.

**Comment by mmollina** [comment]
Hi @baozg, since it's a self, you can duplicate the parent information and provide different names for both parents, even though they will be the same.
