### ISSUE TITLE
using fread in data.table for speed up reading file

### ISSUE THREAD

**Issue by baozg** [mmollina/MAPpoly#46]
Hi, @mmollina 

Can `MAPpoly` change the default `read.delim` to `fread` in `data.table`, it can easily handle the >10k marker.

Thanks.

**Comment by mmollina** [comment]
That's a good idea and I will try to implement it in a near future. If you have the code ready, please send me a pull request and I will incorporate to the main branch.

 However, the bottleneck or reading functions is filtering out non-conforming markers, i.e. given a Mendelan segregation, with no double reduction, remove unexpected genotypic classes.
