### ISSUE TITLE
Grouping

### ISSUE THREAD

**Issue by wittney** [mmollina/MAPpoly#5]
Hi, 

I have provided my code below for the grouping of markers.
ch <- 1
lg <- make_seq_mappoly(lgs, ch)
lg <- make_seq_mappoly(map_input, lg$seq.num[-which(lg$sequence!=ch)])
p <- make_pairs_mappoly(input.twopt = all_pairs_1, input.seq = lg)
m <- rf_list_to_matrix(input.twopt = p, thresh.LOD.ph = 6,
                       thresh.LOD.rf = 6, thresh.rf = 0.25)
plot(m, index = FALSE)
lg.filt <- rf_snp_filter(input.twopt = p, thresh.LOD.ph = 6,
                         thresh.LOD.rf = 6, thresh.rf = 0.25,
                         thresh.perc = 0.05)
plot(m, index = FALSE, ord = lg.filt$seq.mrk.names)
p.filt<- make_pairs_mappoly(input.seq = lg.filt, input.twopt = all_pairs_1)
m.filt<-rf_list_to_matrix(p.filt)
plot(m.filt, index = FALSE)
mds.ord<-mds_mappoly(input.mat = m.filt )
plot(mds.ord)
mds.seq<-make_seq_mappoly(mds.ord)
map.seq<-make_seq_mappoly(map_input, mds.seq$seq.num[-which(is.na(mds.seq$sequence))])
plot(m, ord = map.seq$seq.mrk.names)

my output is below with 4 markers in the mds.ord object. when i run the following step:

mds.ord<-mds_mappoly(input.mat = m.filt )
I receive this output
Stress: 0.12809
Mean Nearest Neighbour Fit: 8.23905Warning messages:
1: In stats::smooth.spline(lambda, xj, ..., df = df, keep.data = FALSE) :
  not using invalid df; must have 1 < df <= n := #{unique x} = 4
2: In stats::smooth.spline(lambda, xj, ..., df = df, keep.data = FALSE) :
  not using invalid df; must have 1 < df <= n := #{unique x} = 4
3: In stats::smooth.spline(lambda, xj, ..., df = df, keep.data = FALSE) :
  not using invalid df; must have 1 < df <= n := #{unique x} = 4
4: In stats::smooth.spline(lambda, xj, ..., df = df, keep.data = FALSE) :
  not using invalid df; must have 1 < df <= n := #{unique x} = 4
map.seq<-make_seq_mappoly(map_input, mds.seq$seq.num[-which(is.na(mds.seq$sequence))])

Also,
map.seq<-make_seq_mappoly(map_input, mds.seq$seq.num[-which(is.na(mds.seq$sequence))])

This is an object of class 'mappoly.sequence'
    ------------------------
    Parameters not estimated
    ------------------------
    Ploidy level:       8 
    No. individuals:    319 
    No. markers:        0 

    No. markers per sequence: not available
    ----------
    No. of markers per dosage in both parents:
 
map.seq has 0 markers. What changes should I make to group and order these 4 markers? Why does the marker number go from 4 to 0 in this step?

map.seq<-make_seq_mappoly(map_input, mds.seq$seq.num[-which(is.na(mds.seq$sequence))])

**Comment by mmollina** [comment]
Could you share the input file (or a small part of it) and the beginning of the script so I can assess the problem? Based only on the script you provided, it is difficult to tell what is going on. You can send it to my e-mail: mmollin@ncsu.edu. I will keep it confidential.
