### ISSUE TITLE
Using MAPpoly for potato population

### ISSUE THREAD

**Issue by jxandyq** [mmollina/MAPpoly#52]
Hello all,
I used the mappoly package to construct the linkage map of a bi-parental 

potato population(tetraploid).It had 303 individuals in all and was sequenced by ddRADseq 

by 2x150bp in illumina company.
I called SNP by Stacks software

(http://catchenlab.life.illinois.edu/stacks/) and called genotype by updog package.
I ran the comand "grs <- group_mappoly(input.mat = mat, expected.groups = 12, comp.mat = TRUE, 

inter = TRUE)",and didn't have the result you provided in the tetra_mappoly_vignette 

(picture attached below).
https://github.com/jxandyq/images/blob/main/Snipaste_2022-02-09_21-00-53.jpg

 The diagonal in the picture indicating the concordance between 

the two sources of information was not very consistent in my data. so I don't know what 

to do next. Any suggestions will be  appreciated.
The code  was as below:
library("mappoly")
dat.dose.csv <- read_geno_csv(file.in  = "f1_dosage.csv", ploidy = 4)
dat.filt.mrk <- filter_missing(input.data = dat.dose.csv, type = "marker", filter.thres = 0.05, inter = TRUE)
dat.filt.ind <- filter_missing(input.data = dat.filt.mrk, type = "individual", filter.thres = 0.025,inter = TRUE)
dat <- dat.filt.ind
pval.bonf <- 0.05/dat$n.mrk
mrks.chi.filt <- filter_segregation(dat, chisq.pval.thres = pval.bonf, inter = TRUE)
seq.init <- make_seq_mappoly(mrks.chi.filt)
all.rf.pairwise <- est_pairwise_rf(input.seq = seq.init,  est.type="disc")
mat <- rf_list_to_matrix(input.twopt = all.rf.pairwise)
grs <- group_mappoly(input.mat = mat, expected.groups = 12, comp.mat = TRUE, inter = TRUE)

Yang
Best regards

**Comment by jxandyq** [comment]
Hello Jeekin,
thanks for your quick respondes.
I haven't tried the method you suggested, I will try it at once.

**Comment by jxandyq** [comment]
Hi Jeekin.
It worked. Thank you again.
I will finish the remaining part.
Yang
best wishes

**Comment by mmollina** [comment]
@jeekinlau  Thanks for your help!
