### ISSUE TITLE
read_geno_csv arguement not passing to table_to_mappoly

### ISSUE THREAD

**Issue by jeekinlau** [mmollina/MAPpoly#55]
https://github.com/mmollina/MAPpoly/blob/e04766ccb4aa03ecc20d6fe763368e78f47401ef/R/read_mappoly_csv.R#L90

i think it should be should be

` return(table_to_mappoly(dat, ploidy, filter.non.conforming , elim.redundant , verbose)) `

**Comment by mmollina** [comment]
Fixed! Thanks for catching that!
