### ISSUE TITLE
filter_missing individual not filtering ind names

### ISSUE THREAD

**Issue by rramadeu** [mmollina/MAPpoly#6]
I used `filter_missing` "individual" and is not filtering the individual's names from input.dat$ind.names object. This is apparently crashing downstream analysis when I'm using `est_full_hmm_with_global_error`. I did the following:

input.data$ind.names<-input.data$ind.names[-rm.ind.id]

and, apparently, fix the issue, but don't know if it is correct...

Cheers,
Rodrigo

**Comment by mmollina** [comment]
Thanks for pointing that out, Rodrigo. The issue should be fixed now.
Please check [this commit](https://github.com/mmollina/MAPpoly/commit/830dbef77df031d55d9ac86eefc3a597aa8c0c91).
